services:
  showcase:
    build:
      context: .
      secrets:
        - GITHUB_ACTOR
        - GITHUB_TOKEN
    image: quarkus-morphium-showcase:local

secrets:
  GITHUB_ACTOR:
    environment: GITHUB_ACTOR
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
