/*
 * Copyright 2025 The Quarkiverse Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quarkiverse.morphium.showcase.importer.entity;

import de.caluga.morphium.annotations.AutoSequence;
import de.caluga.morphium.annotations.CreationTime;
import de.caluga.morphium.annotations.Entity;
import de.caluga.morphium.annotations.Id;
import de.caluga.morphium.annotations.caching.WriteBuffer;
import de.caluga.morphium.driver.MorphiumId;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Morphium entity representing an import record, demonstrating write buffering and bulk operations.
 *
 * <p>This entity showcases two key Morphium features beyond the basics:</p>
 *
 * <h3>{@code @Entity(collectionName = "import_records")}</h3>
 * <p>Maps this class to the {@code import_records} MongoDB collection. Every Morphium entity
 * MUST have this annotation. The {@code collectionName} parameter is optional -- if omitted,
 * Morphium derives the name from the class name using its naming strategy (e.g.,
 * {@code ImportRecord} would become {@code import_record}).</p>
 *
 * <h3>{@code @WriteBuffer} -- Asynchronous Write Buffering</h3>
 * <p>This is one of Morphium's most powerful performance features. Instead of sending every
 * {@code store()} call immediately to MongoDB, Morphium buffers writes in memory and flushes
 * them in batches. The parameters control the buffering behavior:</p>
 * <ul>
 *   <li><b>{@code size = 500}</b> -- Maximum number of write operations to buffer before
 *       triggering an automatic flush. Once 500 pending writes accumulate, they are sent
 *       to MongoDB as a single bulk operation.</li>
 *   <li><b>{@code strategy = WRITE_NEW}</b> -- Determines what happens when the buffer is full
 *       and a new write arrives. {@code WRITE_NEW} means the newest write is sent immediately
 *       while older buffered writes wait for the next flush. Other strategies include:
 *       {@code WRITE_OLD} (flush the oldest buffered write), {@code DEL_OLD} (discard the
 *       oldest buffered write), and {@code IGNORE_NEW} (discard the incoming write).</li>
 *   <li><b>{@code timeout = 5000}</b> -- Maximum time in milliseconds that a write can stay
 *       in the buffer before being flushed, regardless of buffer fill level. This ensures
 *       that even low-throughput scenarios get their writes persisted within 5 seconds.</li>
 * </ul>
 *
 * <p><b>When to use @WriteBuffer:</b> Ideal for high-throughput scenarios like data imports,
 * event logging, or telemetry ingestion where individual write latency is less important
 * than overall throughput. The buffer significantly reduces the number of round-trips to
 * MongoDB by batching multiple writes into fewer bulk operations.</p>
 *
 * <p><b>Caution:</b> Buffered writes are NOT durable until flushed. If the application
 * crashes before a flush, buffered writes are lost. For critical data, either disable
 * buffering or call {@code morphium.flush()} explicitly after important writes.</p>
 *
 * @see de.caluga.morphium.annotations.caching.WriteBuffer
 * @see de.caluga.morphium.annotations.Entity
 */
@Entity(collectionName = "import_records")
@WriteBuffer(size = 500, strategy = WriteBuffer.STRATEGY.WRITE_NEW, timeout = 5000)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldNameConstants
public class ImportRecord {

    /**
     * Unique identifier, auto-generated by Morphium on first store.
     * Mapped to MongoDB's {@code _id} field via the {@code @Id} annotation.
     *
     * @see de.caluga.morphium.annotations.Id
     */
    @Id
    private MorphiumId id;

    /**
     * Sequential import number, automatically assigned by Morphium via {@link AutoSequence}.
     *
     * <p>The {@code @AutoSequence} annotation tells Morphium to assign the next value from
     * the {@code "import_number"} sequence whenever this field is {@code null} at store time.
     * For a single {@code store()}, Morphium calls {@code getNextValue()} (one round-trip).
     * For {@code storeList()}, Morphium calls {@code getNextBatch(n)} — a single
     * lock+increment+unlock regardless of list size.</p>
     *
     * <p>The field must be {@code Long} (boxed), not {@code long} (primitive), so that
     * {@code null} signals "not yet assigned".</p>
     *
     * @see AutoSequence
     * @see de.caluga.morphium.SequenceGenerator
     */
    @AutoSequence(name = "import_number")
    private Long importNumber;

    /** The origin system of this import (e.g., "API", "CSV", "FTP", "S3", "MANUAL"). */
    private String source;

    /** The imported data payload content. */
    private String data;

    /**
     * Status of the import: PENDING, PROCESSED, or ERROR.
     *
     * <p>Demonstrates Morphium's {@code query.set()} for targeted field updates -- the status
     * can be changed to "PROCESSED" without rewriting the entire document. Also demonstrates
     * {@code query.unset()} which removes a field entirely from the MongoDB document.</p>
     */
    private String status;

    /**
     * Timestamp automatically set by Morphium when this record is first persisted.
     *
     * <p>The {@code @CreationTime} annotation causes Morphium to inject the current
     * date/time into this field during the initial {@code store()} call. On subsequent
     * updates, this field remains unchanged, preserving the original import timestamp.</p>
     *
     * @see de.caluga.morphium.annotations.CreationTime
     */
    @CreationTime
    private LocalDateTime importedAt;

    /**
     * List of tags associated with this import record (e.g., "bulk", "auto-generated").
     *
     * <p>Demonstrates Morphium's array manipulation operations:</p>
     * <ul>
     *   <li>{@code morphium.push(query, field, value)} -- appends a value to the array
     *       (MongoDB's {@code $push} operator)</li>
     *   <li>{@code morphium.pull(query, field, value)} -- removes a value from the array
     *       (MongoDB's {@code $pull} operator)</li>
     * </ul>
     * <p>These operations modify the array in-place on the server without loading the
     * document, making them efficient for managing list-valued fields.</p>
     */
    private List<String> tags;
}
