/*
 * Copyright 2025 The Quarkiverse Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quarkiverse.morphium.showcase.audit;

import de.caluga.morphium.Morphium;
import io.quarkiverse.morphium.showcase.audit.entity.AuditEntry;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

/**
 * Application-scoped service that writes audit log entries to MongoDB via Morphium.
 *
 * <p>This class demonstrates the simplest possible Morphium write operation:
 * {@code morphium.store(entity)}. It also showcases how Morphium's {@code @CreationTime}
 * annotation (on {@link AuditEntry#getTimestamp()}) works in practice -- the timestamp
 * field is automatically populated by Morphium during the {@code store()} call, so the
 * caller does not need to set it manually.</p>
 *
 * <h3>How {@code morphium.store()} Works</h3>
 * <ol>
 *   <li>Morphium inspects the entity's {@code @Id} field. If it is {@code null}, Morphium
 *       treats this as an <strong>insert</strong> operation.</li>
 *   <li>Before writing, Morphium processes lifecycle annotations:
 *       {@code @CreationTime} fields are set to the current time, {@code @Version} fields
 *       are initialized, and any {@code @PreStore} callbacks are invoked.</li>
 *   <li>The entity is serialized to a BSON document using Morphium's mapper (applying
 *       name conversion, type mapping, etc.).</li>
 *   <li>The document is inserted into the MongoDB collection determined by the
 *       {@code @Entity(collectionName = "...")} annotation on the entity class.</li>
 *   <li>After insertion, the generated {@code _id} is written back to the entity's
 *       {@code @Id} field, and any {@code @PostStore} callbacks are invoked.</li>
 * </ol>
 *
 * <h3>Capped Collection Behavior</h3>
 * <p>Because {@link AuditEntry} is annotated with {@code @Capped}, Morphium will
 * automatically create the backing collection as a capped collection on the first
 * {@code store()} call (if it does not already exist). Subsequent inserts that exceed
 * the capped limits will cause the oldest documents to be silently removed by MongoDB.</p>
 *
 * @see AuditEntry the entity stored by this listener
 */
@ApplicationScoped
public class AuditListener {

    /**
     * The Morphium ORM instance, injected by CDI. This is the central entry point for
     * all Morphium operations: queries, stores, updates, deletes, aggregations, etc.
     */
    @Inject
    Morphium morphium;

    /**
     * Creates and stores a new audit log entry in MongoDB.
     *
     * <p>Note that we do NOT set the {@code id} or {@code timestamp} fields on the builder.
     * Morphium handles both automatically:</p>
     * <ul>
     *   <li>{@code id} -- Auto-generated by MongoDB as an ObjectId on insert.</li>
     *   <li>{@code timestamp} -- Auto-populated by Morphium's {@code @CreationTime} handler
     *       during the {@code store()} call.</li>
     * </ul>
     *
     * @param entityType the type of entity being audited (e.g., "Product", "Account")
     * @param entityId   the identifier of the specific entity instance
     * @param action     the action performed: "CREATE", "UPDATE", or "DELETE"
     * @param details    a human-readable description of the change
     * @param user       the user or system principal performing the action
     */
    public void log(String entityType, String entityId, String action, String details, String user) {
        AuditEntry entry = AuditEntry.builder()
                .entityType(entityType)
                .entityId(entityId)
                .action(action)
                .details(details)
                .user(user)
                .build();

        // morphium.store() -- The most fundamental Morphium write operation.
        // Since entry.id is null, this will be an INSERT (not an upsert/update).
        // Morphium will:
        //   1. Set the @CreationTime field (timestamp) to LocalDateTime.now()
        //   2. Serialize the entity to BSON using the configured NameProvider (camelCase -> snake_case)
        //   3. Insert the document into the "audit_log" capped collection
        //   4. Write the generated ObjectId back into entry.id
        morphium.store(entry);
    }
}