/*
 * Copyright 2025 The Quarkiverse Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quarkiverse.morphium.showcase.bank.entity;

import de.caluga.morphium.annotations.CreationTime;
import de.caluga.morphium.annotations.Entity;
import de.caluga.morphium.annotations.Id;
import de.caluga.morphium.driver.MorphiumId;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDateTime;

/**
 * Morphium entity representing a money transfer between two bank accounts.
 *
 * <p>This entity serves as an audit log for transfers performed by
 * {@link io.quarkiverse.morphium.showcase.bank.BankService#transfer}. It demonstrates a simple
 * entity with {@code @CreationTime} for automatic timestamp tracking.</p>
 *
 * <p>Unlike {@link Account}, this entity does NOT use {@code @Version} because transfers are
 * write-once records (they are never updated after creation), so optimistic locking is not needed.</p>
 *
 * <p>Design note: The {@code fromAccount} and {@code toAccount} fields store the account number as
 * a string rather than using Morphium's {@code @Reference} annotation. This is a deliberate choice
 * for an audit log -- even if the referenced account is deleted, the transfer record remains intact
 * and readable. Using {@code @Reference} would create a dependency that could result in broken
 * references if accounts were removed.</p>
 */
// @Entity: Maps this class to the "transfers" collection. Each transfer is stored as a separate document.
@Entity(collectionName = "transfers")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldNameConstants
public class Transfer {

    /** The MongoDB document {@code _id}, auto-generated by Morphium on first store. */
    @Id
    private MorphiumId id;

    /** The account number of the sender. Stored as a plain string (not a @Reference). */
    private String fromAccount;

    /** The account number of the recipient. Stored as a plain string (not a @Reference). */
    private String toAccount;

    /** The transfer amount in the specified currency. */
    private double amount;

    /** The currency code for this transfer (e.g., "EUR"). */
    private String currency;

    /** An optional human-readable description of the transfer. */
    private String description;

    /**
     * Timestamp of when this transfer was created.
     *
     * <p>{@code @CreationTime} tells Morphium to automatically populate this field with the
     * current date/time on the first {@code store()} call. This is ideal for audit records
     * where you need to know exactly when an event occurred without manually setting the time.</p>
     */
    // @CreationTime: Morphium sets this automatically on first store. The value is never overwritten on updates.
    @CreationTime
    private LocalDateTime createdAt;

    /**
     * Status of the transfer: PENDING, COMPLETED, or FAILED.
     *
     * <p>In a production system, you might model this as a Java enum. Morphium supports enum fields
     * natively -- they are stored as their string name in MongoDB by default.</p>
     */
    private String status;
}