/*
 * Copyright 2025 The Quarkiverse Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quarkiverse.morphium.showcase.catalog;

import de.caluga.morphium.Morphium;
import io.quarkiverse.morphium.showcase.catalog.entity.Category;
import io.quarkiverse.morphium.showcase.catalog.entity.Product;
import de.caluga.morphium.driver.MorphiumId;
import de.caluga.morphium.query.Query;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import java.util.List;
import java.util.Map;

/**
 * Service layer demonstrating core Morphium CRUD operations, querying, caching, and pagination.
 *
 * <p>This class showcases the most commonly used Morphium API methods:</p>
 * <ul>
 *   <li>{@code morphium.store()} -- Insert or update (upsert) a single entity</li>
 *   <li>{@code morphium.storeList()} -- Bulk-insert a list of entities in one batch</li>
 *   <li>{@code morphium.delete()} -- Remove a single entity by its {@code _id}</li>
 *   <li>{@code morphium.dropCollection()} -- Drop an entire MongoDB collection</li>
 *   <li>{@code morphium.reread()} -- Reload an entity from the database, bypassing cache</li>
 *   <li>{@code morphium.createQueryFor()} -- Build type-safe queries against a collection</li>
 *   <li>{@code morphium.ensureIndicesFor()} -- Create indexes declared via annotations</li>
 *   <li>{@code morphium.getCache()} -- Access the cache manager for statistics and invalidation</li>
 * </ul>
 *
 * <p>The {@link Morphium} instance is injected by the Quarkus CDI container via the
 * quarkus-morphium extension. It is the central entry point for all Morphium operations.</p>
 */
@ApplicationScoped
public class ProductService {

    /**
     * The central Morphium instance, injected by Quarkus CDI.
     * All database operations go through this single entry point.
     */
    @Inject
    Morphium morphium;

    /**
     * Programmatically creates MongoDB indexes declared via {@code @Index} annotations on the
     * {@link Product} entity.
     *
     * <p>Morphium can automatically create indexes on application startup (configured via
     * {@code morphium.auto-index-and-capped-creation-on-write}), but this method allows you to
     * trigger index creation explicitly. It reads the {@code @Index} annotations on the entity
     * class and issues the corresponding {@code createIndex} commands to MongoDB.</p>
     */
    public void ensureIndexes() {
        // ensureIndicesFor() scans @Index annotations on the entity class and creates them in MongoDB.
        // This is idempotent -- calling it multiple times is safe; MongoDB skips already-existing indexes.
        morphium.ensureIndicesFor(Product.class);
    }

    /**
     * Retrieves all products from the "products" collection.
     *
     * @return a list of all products; empty list if the collection is empty
     */
    public List<Product> findAll() {
        // createQueryFor() starts building a type-safe query for the given entity class.
        // asList() executes the query and returns all matching documents as a Java List.
        // Because Product is @Cache-annotated, results may be served from Morphium's read cache.
        return morphium.createQueryFor(Product.class).asList();
    }

    /**
     * Finds a single product by its MongoDB ObjectId.
     *
     * @param id the string representation of the MorphiumId (MongoDB ObjectId)
     * @return the matching product, or {@code null} if not found
     */
    public Product findById(String id) {
        // f() selects a field to filter on. Product.Fields.id is a compile-time-safe field name
        // constant generated by Lombok's @FieldNameConstants. eq() adds an equality filter.
        // get() executes the query and returns a single result (or null).
        return morphium.createQueryFor(Product.class)
                .f(Product.Fields.id).eq(new MorphiumId(id))
                .get();
    }

    /**
     * Finds products with an exact name match.
     *
     * @param name the exact product name to search for
     * @return a list of matching products
     */
    public List<Product> findByName(String name) {
        // Simple equality query: WHERE name = ?
        return morphium.createQueryFor(Product.class)
                .f(Product.Fields.name).eq(name)
                .asList();
    }

    /**
     * Searches products by name using a regex pattern (case-insensitive).
     *
     * @param pattern the search pattern (will be wrapped in a case-insensitive regex)
     * @return a list of products whose name matches the pattern
     */
    public List<Product> searchByName(String pattern) {
        // matches() translates to MongoDB's $regex operator. The "(?i)" prefix makes it
        // case-insensitive. This is equivalent to: { name: { $regex: "(?i)pattern" } }
        return morphium.createQueryFor(Product.class)
                .f(Product.Fields.name).matches("(?i)" + pattern)
                .asList();
    }

    /**
     * Finds products within a price range, sorted by price ascending.
     *
     * <p>Demonstrates Morphium's range query operators {@code gte()} and {@code lte()}, as well as
     * sorting with {@code sort()}.</p>
     *
     * @param min minimum price (inclusive)
     * @param max maximum price (inclusive)
     * @return products within the given price range, sorted by price ascending
     */
    public List<Product> findByPriceRange(double min, double max) {
        // gte()/lte() map to MongoDB's $gte/$lte operators.
        // Multiple f() calls on different constraints are combined with AND.
        // sort() takes a Map of field -> direction (1 = ascending, -1 = descending).
        return morphium.createQueryFor(Product.class)
                .f(Product.Fields.price).gte(min)
                .f(Product.Fields.price).lte(max)
                .sort(Map.of(Product.Fields.price, 1))
                .asList();
    }

    /**
     * Finds products by their embedded category name.
     *
     * <p>Demonstrates querying into embedded (nested) documents using MongoDB dot notation.
     * Since {@link Category} is {@code @Embedded} inside {@link Product}, its fields are accessed
     * as {@code "category.name"} in the query.</p>
     *
     * @param categoryName the category name to filter on
     * @return products belonging to the specified category
     */
    public List<Product> findByCategory(String categoryName) {
        // Dot notation "category.name" reaches into the embedded Category sub-document.
        // This works because Category is @Embedded, so it's stored inline within the Product document.
        return morphium.createQueryFor(Product.class)
                .f("category.name").eq(categoryName)
                .asList();
    }

    /**
     * Counts the total number of products in the collection.
     *
     * @return the document count
     */
    public long count() {
        // countAll() executes a MongoDB count command. It is more efficient than fetching all
        // documents and counting in Java, as MongoDB handles the count on the server side.
        return morphium.createQueryFor(Product.class).countAll();
    }

    /**
     * Stores (inserts or updates) a product.
     *
     * <p>If the product's {@code id} is {@code null}, Morphium performs an insert and generates a new
     * MorphiumId. If the {@code id} is set and a document with that id already exists, Morphium
     * performs an update (replace).</p>
     *
     * @param product the product to store
     * @return the stored product (with id populated if it was a new insert)
     */
    public Product store(Product product) {
        // store() is Morphium's primary write operation. It performs an upsert:
        // - New entity (id == null): inserts a new document, sets the generated id on the object
        // - Existing entity (id != null): replaces the entire document in MongoDB
        morphium.store(product);
        return product;
    }

    /**
     * Creates a new product with the given attributes and persists it.
     *
     * @param name         the product name
     * @param description  the product description
     * @param price        the product price
     * @param stock        the stock quantity
     * @param categoryName the category name (will be embedded)
     * @param categoryDesc the category description (will be embedded)
     * @param tags         a list of tags
     * @return the newly created and persisted product
     */
    public Product create(String name, String description, double price, int stock,
                          String categoryName, String categoryDesc, List<String> tags) {
        Product product = Product.builder()
                .name(name)
                .description(description)
                .price(price)
                .stock(stock)
                .category(new Category(categoryName, categoryDesc))
                .tags(tags)
                .build();
        // store() detects that id is null, so it inserts a new document and populates the id field.
        morphium.store(product);
        return product;
    }

    /**
     * Deletes a product by its id.
     *
     * @param id the string representation of the product's MorphiumId
     */
    public void delete(String id) {
        Product product = findById(id);
        if (product != null) {
            // delete() removes the document matching this entity's @Id from MongoDB.
            // Morphium also invalidates any cached entries for this entity.
            morphium.delete(product);
        }
    }

    /**
     * Drops the entire "products" collection from MongoDB.
     *
     * <p>{@code dropCollection()} is a destructive operation that removes the collection and all
     * its indexes. It is useful for test setup/teardown or for a "reset all data" feature.</p>
     */
    public void deleteAll() {
        // dropCollection() removes the entire MongoDB collection, including all documents and indexes.
        // This is much faster than deleting documents one by one, but it also removes indexes.
        morphium.dropCollection(Product.class);
    }

    /**
     * Re-reads (reloads) a product from the database, bypassing the cache.
     *
     * <p>Morphium's {@code reread()} fetches the latest version of the document from MongoDB and
     * updates the Java object's fields in-place. This is useful when you suspect the cached version
     * might be stale, or after another process may have modified the document.</p>
     *
     * @param product the product to reload (must have a valid id)
     * @return the same product instance, now updated with the latest data from MongoDB
     */
    public Product reread(Product product) {
        // reread() bypasses the Morphium cache and reads directly from MongoDB.
        // The object's fields are updated in-place -- no new object is created.
        morphium.reread(product);
        return product;
    }

    /**
     * Returns Morphium cache statistics, useful for monitoring and debugging cache behavior.
     *
     * @return a map containing cache sizes and general Morphium statistics
     */
    public Map<String, Object> getCacheStats() {
        // getStatistics() returns counters for reads, writes, cache hits, cache misses, etc.
        var stats = morphium.getStatistics();
        // getCache().getSizes() returns the current number of cached entries per entity type.
        var cacheSizes = morphium.getCache().getSizes();
        return Map.of(
                "cacheSizes", cacheSizes,
                "statistics", stats
        );
    }

    /**
     * Clears the Morphium read cache for the {@link Product} entity.
     *
     * <p>After calling this, the next query for products will go directly to MongoDB instead of
     * being served from cache. Morphium automatically invalidates the cache on writes, but this
     * method is useful when external processes modify the data outside of Morphium.</p>
     */
    public void clearCache() {
        // clearCachefor() removes all cached query results for a specific entity class.
        // You can also use clearCacheIfNecessary() or resetCache() for broader invalidation.
        morphium.getCache().clearCachefor(Product.class);
    }

    /**
     * Finds products with pagination (skip/limit) and sorting.
     *
     * <p>Demonstrates Morphium's built-in pagination support using {@code skip()} and {@code limit()},
     * which map directly to MongoDB's skip/limit cursor modifiers.</p>
     *
     * @param skip      the number of documents to skip (offset)
     * @param limit     the maximum number of documents to return
     * @param sortField the field to sort by (use Product.Fields constants)
     * @param sortDir   the sort direction: 1 for ascending, -1 for descending
     * @return a page of products
     */
    public List<Product> findWithPagination(int skip, int limit, String sortField, int sortDir) {
        // sort() + skip() + limit() together implement server-side pagination.
        // This is efficient because MongoDB applies skip/limit on the cursor, not in Java memory.
        return morphium.createQueryFor(Product.class)
                .sort(Map.of(sortField, sortDir))
                .skip(skip)
                .limit(limit)
                .asList();
    }

    /**
     * Seeds the collection with sample product data if it is currently empty.
     *
     * <p>Uses {@code morphium.storeList()} to insert multiple products in a single batch operation,
     * which is significantly more efficient than calling {@code store()} individually for each product.</p>
     */
    public void seedData() {
        if (count() > 0) return;

        List<Product> products = List.of(
                Product.builder().name("Laptop Pro 15").description("High-performance laptop").price(1299.99).stock(50)
                        .category(new Category("Electronics", "Computers & Accessories")).tags(List.of("laptop", "pro", "portable")).build(),
                Product.builder().name("Wireless Mouse").description("Ergonomic wireless mouse").price(29.99).stock(200)
                        .category(new Category("Electronics", "Peripherals")).tags(List.of("mouse", "wireless", "ergonomic")).build(),
                Product.builder().name("Standing Desk").description("Adjustable height standing desk").price(449.00).stock(30)
                        .category(new Category("Furniture", "Office")).tags(List.of("desk", "standing", "ergonomic")).build(),
                Product.builder().name("Mechanical Keyboard").description("Cherry MX Blue switches").price(89.99).stock(120)
                        .category(new Category("Electronics", "Peripherals")).tags(List.of("keyboard", "mechanical", "gaming")).build(),
                Product.builder().name("Monitor 27\"").description("4K IPS display").price(399.99).stock(75)
                        .category(new Category("Electronics", "Displays")).tags(List.of("monitor", "4k", "ips")).build(),
                Product.builder().name("USB-C Hub").description("7-in-1 USB-C adapter").price(49.99).stock(300)
                        .category(new Category("Electronics", "Accessories")).tags(List.of("usb-c", "hub", "adapter")).build(),
                Product.builder().name("Office Chair").description("Mesh back ergonomic chair").price(299.00).stock(45)
                        .category(new Category("Furniture", "Office")).tags(List.of("chair", "ergonomic", "office")).build(),
                Product.builder().name("Webcam HD").description("1080p webcam with mic").price(59.99).stock(150)
                        .category(new Category("Electronics", "Accessories")).tags(List.of("webcam", "hd", "streaming")).build()
        );
        // storeList() performs a bulk insert, sending all documents to MongoDB in one batch.
        // This is much more efficient than calling store() in a loop, as it reduces network round-trips.
        morphium.storeList(products);
    }
}