/*
 * Copyright 2025 The Quarkiverse Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quarkiverse.morphium.showcase.geo.entity;

import de.caluga.morphium.annotations.Entity;
import de.caluga.morphium.annotations.Id;
import de.caluga.morphium.annotations.Index;
import de.caluga.morphium.driver.MorphiumId;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.util.List;

/**
 * Morphium entity representing a physical store location, demonstrating
 * <strong>geospatial data storage</strong> and <strong>index management</strong>.
 *
 * <h3>Key Morphium Features Demonstrated</h3>
 * <ul>
 *   <li>{@code @Entity(collectionName = "stores")} -- Maps this class to the {@code stores}
 *       MongoDB collection. As with all Morphium entities, the {@code collectionName} attribute
 *       explicitly controls the MongoDB collection name.</li>
 *   <li>{@code @Id} with {@link MorphiumId} -- The mandatory primary key field.</li>
 *   <li>{@code @Index} on the {@code name} field -- Creates a single-field index for
 *       efficient store lookups by name.</li>
 *   <li>{@code @FieldNameConstants} -- Lombok generates a {@code Fields} inner class with
 *       string constants for each field, enabling type-safe query construction (e.g.,
 *       {@code Store.Fields.id}, {@code Store.Fields.name}).</li>
 * </ul>
 *
 * <h3>Geospatial Data in MongoDB</h3>
 * <p>The {@code location} field stores coordinates as a {@code double[]} array in
 * <strong>[longitude, latitude]</strong> order (GeoJSON convention). MongoDB supports two
 * types of geospatial indexes:</p>
 * <ul>
 *   <li><strong>2dsphere</strong> -- For spherical (Earth-like) geometry. Supports operators
 *       like {@code $nearSphere}, {@code $geoWithin}, and {@code $geoIntersects}. This is
 *       the recommended index type for real-world geographic queries.</li>
 *   <li><strong>2d</strong> -- For flat, Euclidean geometry. Simpler but less accurate for
 *       geographic distances.</li>
 * </ul>
 * <p>To use geospatial queries, you need to create a 2dsphere index on the location field.
 * This can be done via {@code morphium.ensureIndicesFor(Store.class)} (see
 * {@link io.quarkiverse.morphium.showcase.geo.GeoService}) or by adding an
 * {@code @Index} annotation with a specific index definition.</p>
 *
 * <h3>Array Fields in Morphium</h3>
 * <p>Both {@code location} ({@code double[]}) and {@code services} ({@code List<String>})
 * demonstrate how Morphium handles array-like data. Morphium automatically serializes:</p>
 * <ul>
 *   <li>Java arrays ({@code double[]}, {@code String[]}) as BSON arrays</li>
 *   <li>Java collections ({@code List<String>}) as BSON arrays</li>
 * </ul>
 * <p>No special annotation is needed -- Morphium handles the conversion transparently.</p>
 *
 * @see io.quarkiverse.morphium.showcase.geo.GeoService GeoService for CRUD and geo queries
 */
// @Entity -- Maps this class to the "stores" MongoDB collection.
@Entity(collectionName = "stores")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldNameConstants
public class Store {

    /**
     * The unique document identifier, mapped to MongoDB's {@code _id} field.
     *
     * <p>{@link MorphiumId} is Morphium's own ObjectId type. It is auto-generated by
     * MongoDB when not explicitly set before storing.</p>
     */
    @Id
    private MorphiumId id;

    /**
     * The display name of the store (e.g., "Munich Store").
     *
     * <p>{@code @Index} creates a single-field ascending index on this field, enabling
     * fast lookups and text searches by store name.</p>
     */
    @Index
    private String name;

    /**
     * The street address of the store. Stored as-is in MongoDB with no special indexing.
     */
    private String address;

    /**
     * The city where the store is located.
     */
    private String city;

    /**
     * The country where the store is located.
     */
    private String country;

    /**
     * Geospatial coordinates stored as {@code [longitude, latitude]}.
     *
     * <p><strong>Important:</strong> MongoDB's GeoJSON convention requires coordinates in
     * <strong>[longitude, latitude]</strong> order (not latitude, longitude as is common
     * in everyday usage). Getting this order wrong is one of the most common mistakes
     * when working with geospatial data in MongoDB.</p>
     *
     * <p>Morphium serializes this {@code double[]} directly as a BSON array. To enable
     * geospatial queries like {@code $nearSphere}, you would create a 2dsphere index
     * on this field using MongoDB's index creation commands or Morphium's
     * {@code ensureIndicesFor()} method.</p>
     *
     * <p>For more advanced GeoJSON support (Point, LineString, Polygon), you would
     * typically use a nested document with {@code type} and {@code coordinates} fields.
     * The simple array format shown here works with MongoDB's legacy coordinate pairs.</p>
     */
    private double[] location;

    /**
     * The store's phone number. A simple string field with no special Morphium behavior.
     */
    private String phone;

    /**
     * A list of services offered by this store (e.g., "Repair", "Sales", "Consultation").
     *
     * <p>Morphium serializes {@code List<String>} as a BSON array in MongoDB. You can
     * query array fields using Morphium's query API -- for example, to find all stores
     * that offer "Repair", you would use:
     * {@code query.f("services").eq("Repair")} (MongoDB's array element matching).</p>
     */
    private List<String> services;
}