/*
 * Copyright 2025 The Quarkiverse Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.quarkiverse.morphium.showcase.blog.entity;

import de.caluga.morphium.annotations.*;
import de.caluga.morphium.annotations.lifecycle.Lifecycle;
import de.caluga.morphium.annotations.lifecycle.PreStore;
import de.caluga.morphium.annotations.lifecycle.PostLoad;
import de.caluga.morphium.driver.MorphiumId;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Morphium entity representing a blog post -- the richest entity in this showcase, demonstrating
 * nearly every Morphium annotation in a single class.
 *
 * <p>Annotations demonstrated:</p>
 * <ul>
 *   <li><strong>{@code @Entity}</strong> -- Maps to the "blog_posts" collection.</li>
 *   <li><strong>{@code @Lifecycle}</strong> -- Enables lifecycle callbacks ({@code @PreStore}, {@code @PostLoad}).
 *       Without this class-level annotation, Morphium ignores lifecycle method annotations.</li>
 *   <li><strong>{@code @Id}</strong> -- MongoDB document primary key.</li>
 *   <li><strong>{@code @Index}</strong> -- Single-field index on title.</li>
 *   <li><strong>{@code @Version}</strong> -- Optimistic locking version counter.</li>
 *   <li><strong>{@code @CreationTime}</strong> -- Auto-set on first store (never overwritten).</li>
 *   <li><strong>{@code @LastChange}</strong> -- Auto-updated on every store (tracks last modification).</li>
 *   <li><strong>{@code @LastAccess}</strong> -- Auto-updated on every read (tracks last access time).</li>
 *   <li><strong>{@code @Reference}</strong> -- Stores a link to an Author document in a separate collection.
 *       With {@code automaticStore = true} (the default), Morphium auto-stores the referenced entity
 *       if it lacks an ID. Additional options: {@code cascadeDelete = true} to delete the referenced
 *       entity when the parent is deleted, {@code orphanRemoval = true} to delete entities removed
 *       from the reference during an update.</li>
 *   <li><strong>{@code @Reference(lazyLoading = true)}</strong> -- Like @Reference, but the referenced
 *       object is not loaded from the database until it is actually accessed (lazy proxy).</li>
 *   <li><strong>{@code @Transient}</strong> -- Field is excluded from MongoDB storage entirely.</li>
 *   <li><strong>{@code @PreStore}</strong> -- Lifecycle callback invoked just before the entity is written.</li>
 *   <li><strong>{@code @PostLoad}</strong> -- Lifecycle callback invoked just after the entity is loaded.</li>
 * </ul>
 *
 * <h3>Embedded comments vs Referenced authors</h3>
 * <p>Comments are stored as embedded sub-documents (inside the BlogPost document) because they
 * belong to exactly one post and are always loaded together. Authors are stored in a separate
 * collection and linked via {@code @Reference} because they are shared across multiple posts.</p>
 *
 * <h3>Lifecycle callbacks</h3>
 * <p>Morphium invokes lifecycle methods at specific points in the persistence lifecycle:</p>
 * <ol>
 *   <li>{@code @PreStore} -- Before the entity is written to MongoDB. Use for validation, default values,
 *       or computing derived fields.</li>
 *   <li>{@code @PostStore} -- After the entity is written to MongoDB.</li>
 *   <li>{@code @PostLoad} -- After the entity is loaded from MongoDB. Use for enrichment or cache warming.</li>
 *   <li>{@code @PreRemove} / {@code @PostRemove} -- Before/after deletion.</li>
 * </ol>
 */
// @Entity: Maps this class to the "blog_posts" collection in MongoDB.
@Entity(collectionName = "blog_posts")
// @Lifecycle: REQUIRED class-level annotation to enable lifecycle callbacks (@PreStore, @PostLoad, etc.).
// Without this annotation, Morphium silently ignores all lifecycle method annotations on the entity.
@Lifecycle
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldNameConstants
public class BlogPost {

    /** MongoDB document {@code _id}. Auto-generated by Morphium on first store if null. */
    @Id
    private MorphiumId id;

    /**
     * The blog post title, with a single-field ascending index for fast title lookups.
     * {@code @Index} without options creates a standard ascending index: {@code {title: 1}}.
     */
    @Index
    private String title;

    /** The full blog post content. Stored as a plain string field -- no index needed for full content. */
    private String content;

    /**
     * Optimistic locking version counter.
     *
     * <p>{@code @Version} enables optimistic concurrency control. On every {@code store()} call,
     * Morphium checks that the database version matches, then increments it. If there is a mismatch
     * (another process updated the document since it was read), a {@code VersionMismatchException}
     * is thrown. See {@link io.quarkiverse.morphium.showcase.blog.BlogService#updatePost} for
     * an example of catching and handling this exception.</p>
     */
    // @Version: Managed by Morphium. Never set this manually -- Morphium reads, checks, and increments it.
    @Version
    private Long version;

    /**
     * Timestamp of when this post was first created.
     *
     * <p>{@code @CreationTime} is set automatically by Morphium on the first {@code store()} call.
     * It is never overwritten on subsequent updates. This differs from {@code @LastChange}, which
     * is updated on every write.</p>
     */
    // @CreationTime: Set once on insert, immutable afterwards. Perfect for "created at" fields.
    @CreationTime
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last modification.
     *
     * <p>{@code @LastChange} is automatically updated by Morphium every time {@code store()} is
     * called on this entity. Together with {@code @CreationTime}, this provides a complete audit
     * trail of when the document was created and last modified.</p>
     */
    // @LastChange: Updated by Morphium on every store() call. Unlike @CreationTime, this changes on updates.
    @LastChange
    private LocalDateTime lastChanged;

    /**
     * Timestamp of the last time this document was read from the database.
     *
     * <p>{@code @LastAccess} is automatically updated by Morphium every time the entity is loaded
     * (via queries, findById, etc.). This can be useful for tracking "popularity" or implementing
     * time-based data retention policies. Note that this causes a write on every read, which may
     * have performance implications for frequently accessed entities.</p>
     */
    // @LastAccess: Updated by Morphium on every read. Be aware this generates a write for each read operation.
    @LastAccess
    private LocalDateTime lastAccessed;

    /**
     * The blog post's author, stored as a reference to a document in the "authors" collection.
     *
     * <p>{@code @Reference} tells Morphium NOT to embed the Author object inline. Instead, Morphium
     * stores only the author's {@code _id} in the blog post document. When the BlogPost is loaded,
     * Morphium automatically resolves the reference by querying the "authors" collection.</p>
     *
     * <p>The resulting MongoDB document looks like:</p>
     * <pre>{@code
     * {
     *   "_id": ObjectId("..."),
     *   "title": "My Post",
     *   "author": { "$ref": "authors", "$id": ObjectId("...") }
     * }
     * }</pre>
     */
    // @Reference: Stores only the author's _id in this document. Morphium resolves it on load (eager by default).
    // With automaticStore=true (default), Morphium auto-stores the Author if it has no ID yet.
    // Optional: cascadeDelete=true would delete the Author when this BlogPost is deleted.
    @Reference
    private Author author;

    /**
     * An optional reviewer, loaded lazily.
     *
     * <p>{@code @Reference(lazyLoading = true)} creates a lazy proxy instead of immediately loading
     * the referenced Author from the database. The actual database query is deferred until a method
     * on the reviewer object is called (e.g., {@code getReviewer().getDisplayName()}). This is useful
     * for references that are rarely accessed, as it avoids unnecessary database round-trips.</p>
     *
     * <p>{@code cascadeDelete = true} means that when this BlogPost is deleted via
     * {@code morphium.delete(post)}, the referenced reviewer Author is automatically deleted as well.
     * Compare with the {@code author} field above which does NOT use cascade — deleting a post leaves
     * the author intact because it may be shared across multiple posts.</p>
     *
     * <p>Under the hood, Morphium creates a proxy (using Java dynamic proxies or cglib) that intercepts
     * method calls and triggers the load on first access.</p>
     */
    // @Reference(lazyLoading = true): The Author is NOT loaded from DB until you actually call a method on it.
    // This saves a DB round-trip if the reviewer is never accessed in a given request.
    // cascadeDelete = true: When this BlogPost is deleted, the reviewer Author is deleted too.
    // Compare with "author" above (no cascade) — a shared reference where cascade would be dangerous.
    @Reference(lazyLoading = true, cascadeDelete = true)
    private Author reviewer;

    /**
     * Comments on this blog post, stored as embedded sub-documents.
     *
     * <p>Because {@link Comment} is annotated with {@code @Embedded}, each comment is stored directly
     * inside the BlogPost document as an element in a JSON array. This is MongoDB's "denormalized"
     * data model -- all comments live within the parent document, making reads very fast (single
     * document fetch), but limiting the total size to MongoDB's 16MB document limit.</p>
     */
    @Builder.Default
    private List<Comment> comments = new ArrayList<>();

    /**
     * Tags associated with this post. Stored as a simple JSON array of strings in MongoDB.
     * Morphium natively serializes {@code List<String>} without any special annotations.
     */
    @Builder.Default
    private List<String> tags = new ArrayList<>();

    /**
     * Arbitrary key-value metadata. Stored as a sub-document in MongoDB.
     * Morphium natively serializes {@code Map<String, String>} as a MongoDB sub-document.
     */
    @Builder.Default
    private Map<String, String> metadata = new HashMap<>();

    /** Whether the post has been published. Simple boolean field, stored as-is in MongoDB. */
    private boolean published;

    /**
     * A transient field that is NEVER stored in MongoDB.
     *
     * <p>{@code @Transient} (Morphium's annotation) tells Morphium to completely ignore this field
     * during serialization and deserialization. The Java {@code transient} keyword is also used here
     * for additional safety (it prevents Java serialization as well), but Morphium's {@code @Transient}
     * annotation is what controls the MongoDB behavior.</p>
     *
     * <p>Use cases for transient fields include: temporary UI state, computed values that should not
     * be persisted, or fields used only during processing.</p>
     */
    // @Transient: Morphium skips this field entirely -- it is never written to or read from MongoDB.
    @Transient
    private transient String editNote;

    /**
     * Lifecycle callback: invoked by Morphium just BEFORE this entity is written to MongoDB.
     *
     * <p>{@code @PreStore} methods run synchronously before the store/update operation. They are
     * useful for:</p>
     * <ul>
     *   <li>Initializing null collections to empty lists (preventing NPEs in MongoDB queries)</li>
     *   <li>Computing derived fields (e.g., a "wordCount" field based on content length)</li>
     *   <li>Validation (throw an exception to abort the store)</li>
     * </ul>
     *
     * <p><strong>Requirement:</strong> The class MUST be annotated with {@code @Lifecycle} for this
     * callback to be invoked.</p>
     */
    // @PreStore: Called by Morphium before persisting. Ensures collections are never null in the DB.
    @PreStore
    public void onPreStore() {
        if (tags == null) {
            tags = new ArrayList<>();
        }
        if (metadata == null) {
            metadata = new HashMap<>();
        }
    }

    /**
     * Lifecycle callback: invoked by Morphium just AFTER this entity is loaded from MongoDB.
     *
     * <p>{@code @PostLoad} methods run after Morphium has populated all fields from the MongoDB
     * document. They are useful for:</p>
     * <ul>
     *   <li>Computing transient/derived fields that are not stored in the database</li>
     *   <li>Post-load validation or data migration</li>
     *   <li>Initializing transient state needed by the application</li>
     * </ul>
     */
    // @PostLoad: Called by Morphium after reading from MongoDB. Use for enrichment, validation, or migration.
    @PostLoad
    public void onPostLoad() {
        // Could perform validation or enrichment after loading
    }
}